import type { Metadata } from "next";
import "./globals.css";

import { Montserrat, Mystery_Quest } from "next/font/google";
import MaxWidthWrapper from "@/components/max-width-wrapper";
import Footer from "@/components/footer";
import Navbar from "@/components/navbar";

const mysteryQuest = Mystery_Quest({
	weight: "400",
	subsets: ["latin"],
	variable: "--font-mysteryQuest",
});

const montserrat = Montserrat({
	weight: ["400", "500", "600", "700"],
	subsets: ["latin"],
	variable: "--font-montserrat",
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en">
			<body
				className={`${mysteryQuest.variable} ${montserrat.variable} min-h-screen relative`}>
				<MaxWidthWrapper>
					<Navbar />
					{children}
				</MaxWidthWrapper>
				<Footer />
			</body>
		</html>
	);
}
